echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-26 and learning DevOps"
echo "Hello, Good morning!"
echo "Adding new value 2"
echo "Adding one more line-1"
echo "Line 2"
